name: Production Workflow

on:
  pull_request:
    paths:
      - '.github/workflows/production_workflow.yml'
      - production/*
    types:
      - closed
  workflow_dispatch:

jobs:
  build_and_deploy:
    if: github.event_name == 'workflow_dispatch' || (github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'master')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GithubActionsRoleSession

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Download model from S3
        # uses: keithweaver/aws-s3-github-action@v1.0.0
        # with:
        #   command: cp
        #   aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        #   aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #   aws_region: ${{ secrets.AWS_REGION }}
        #   source: ${{ secrets.AWS_S3_MODEL_PATH }}
        #   destination: ./production/models/model.tar.gz
        run: aws s3 cp s3://${{ secrets.AWS_S3_BUCKET_NAME }}.${{ secrets.AWS_S3_MODEL_PATH }} ./production/models/.

      - name: Extract model
        run: tar -xvf ./production/models/model.tar.gz

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./production/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.PRODUCTION_IMAGE_NAME }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.PRODUCTION_IMAGE_NAME }}:${{ github.sha }}
    