name: Training Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  train_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GithubActionsRoleSession
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.10

      - name: Test and build translation package
        run: |
          cd packages/translation/src
          pip install --upgrade pip
          pip install coverage==7.4.3 wheel==0.42.0 setuptools==65.5.0
          pip install -r ../requirements.txt
          coverage run -m unittest discover -s . -p 'test_*.py' && coverage report -m --fail-under=20
          cd ..
          python setup.py sdist bdist_wheel
          cp dist/*.whl ../../experiment/train/src/steps/data_processing/.
          cp dist/*.whl ../../experiment/train/src/steps/training/.

      - name: Install Dependencies
        run: |
          pip install sagemaker==2.204.0

      - name: SageMaker Training
        run: |
          cd experiment/train
          python pipeline_train.py \
          --s3-bucket-name ${{ secrets.AWS_S3_BUCKET_NAME }}
